version: '3.1'

services:
  source:
    env_file: .env
    privileged: true
    container_name: "source"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.source
    mac_address: ${MAC_SOURCE}
    networks:
      app_net:
        ipv4_address: ${IP_SOURCE}

  target:
    env_file: .env
    privileged: true
    container_name: "target"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.target
    mac_address: ${MAC_TARGET}
    networks:
      app_net:
        ipv4_address: ${IP_TARGET}

  ft_malcolm:
    env_file: .env
    container_name: "ft_malcolm"
    privileged: true
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.ft_malcolm
    mac_address: "02:42:ac:11:00:04"
    networks:
      app_net:
        ipv4_address: 172.16.238.30

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24